### ISSUE TITLE
IQTable.inheritColumns works only for depth 3

### ISSUE THREAD

**Issue by Maaartinus** [gitblit/iciql#13]
The documentation to `IQTable.inheritColumns` says

> The inherit columns allows this model class to inherit columns from its super class. Any IQTable annotation present on the super class is ignored.

The second sentence is wrong as `TableDefinition.mapFields` tests `superTable.inheritColumns`. Unfortunately, it doesn't go any further. This is a bad surprise, when you make the class hierarchy deeper.

I'd suggest to iterate the whole hierarchy up to a class having no such annotation. I could provide a patch, if wanted.

**Comment by gitblit** [comment]
> I could provide a patch, if wanted

Please open a PR.

**Comment by gitblit** [comment]
Closed by #14
