### ISSUE TITLE
IQColumn length with trim not working for DSL

### ISSUE THREAD

**Issue by nickelc** [gitblit/iciql#15]
The behavior of the dsl should be the same as for db.insert(record)

**Comment by gitblit** [comment]
I'm on vacation for a week or so. I'll make time to review when I return.  Pull requests welcome. :)

**Comment by nickelc** [comment]
The trim functionality is in TableDefinition.getValue. I don't know, what the best approach is to get it in UpdateColumnSet and in case if the value come as parameter.

A pull request for a test is possible.
