### ISSUE TITLE
imcomplete maven description

### ISSUE THREAD

**Issue by tos-kamiya** [gitblit/iciql#16]
Hi,

It looks that http://gitblit.github.io/iciql/maven/ is missing a `<dependency>` section.

As far as I've tried, I need to add a `<dependency>` section in pom.xml, like:
```
  <repositories>
    <repository>
      <id>com.iciql</id>
      <name>Iciql</name>
      <url>http://gitblit.github.io/iciql/maven/</url>
      <layout>default</layout>
    </repository>
  </repositories>
  <dependencies>
    <dependency>
      <groupId>com.iciql</groupId>
      <artifactId>iciql</artifactId>
      <version>1.6.4</version>
    </dependency>
  </dependencies>
```

Thank you in advance,

**Comment by gitblit** [comment]
I'm in the process of moving to MavenCentral.  The docs will get revised to reflect this.
