### ISSUE TITLE
The "where" compile-time statement did not work with "String" type field

### ISSUE THREAD

**Issue by qikh** [gitblit/iciql#24]
The model class is:
```
@IQTable
class User {
    @IQColumn(primaryKey = true, autoIncrement = true)
    var id: Long = 0
    @IQColumn
    var name: String? = null
}
```

The SQL DSL is working with id field:
```
val user = User()
val users = db.from(user).where(user.id).`is`(1).select()
```

The SQL DSL is NOT working with "String" type filed:
```
val user = User()
val users = db.from(user).where(user.name).`is`("Tom").select()
```

The above code will generate compile error.

It looked the method 
```
public <A> QueryCondition<T, A> where(A x)
```
was conflict with method 
```
public QueryWhere<T> where(String fragment, Object... args)
```
when the filed type is "String".

**Comment by gitblit** [comment]
Hmm, yes I see.

**Comment by gitblit** [comment]
Actually, Java doesn't fail.  Is that Kotlin or Ceylon?  Looks like an interop problem.

I added a method for `where(String)` which may help you.  2.1.1 release will be on MavenCentral shortly.

**Comment by qikh** [comment]
Yes, the code is in Kotlin. The new method would be helpful.
