### ISSUE TITLE
 JdbcUtils.DRIVERS.db2: "COM.ibm.db2.jdbc.net.DB2Driver" ???

### ISSUE THREAD

**Issue by elseorand** [gitblit/iciql#27]
Hi,

I develop a system based on DB2, and I'd like to use this for testing.
However JDBC drivers provided by IBM in http://www-01.ibm.com/support/docview.wss?uid=swg21601089 are 
"com.ibm.db2.jcc.DB2Driver" and "COM.ibm.db2.jdbc.app.DB2Driver".

Is "COM.ibm.db2.jdbc.net.DB2Driver" right name?

**Comment by gitblit** [comment]
I've never used DB2, but after translating that page I think you want `Com.ibm.db2.jcc.DB2Driver` which is the JDBC Type 4 driver.  The `COM` one is a Type 2 and described as *legacy*.

**Comment by elseorand** [comment]
Thank you.
Please look at "app" in the provided driver name "COM.ibm.db2.jdbc. **app** .DB2Driver",
but JdbcUtils.DRIVERS. db2's name has "net" ("COM.ibm.db2.jdbc. **net** .DB2Driver").
Is this right ?

**Comment by gitblit** [comment]
Closed by #28
